django_homework/first_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='first_page'),
    path('call_order/', views.order_call, name='order_call'),
    path('success/', views.success, name='success'),
    path('tracker/', views.tracker, name='tracker'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('note_create/', views.note_create, name='note_create'),
    path('note_detail/<int:pk>/', views.note_detail, name='note_detail'),
    path('notes/', views.note_list, name='note_list'),
    path('note_edit/<int:pk>/', views.note_edit, name='note_edit'),
    path('note_delete/<int:pk>/', views.note_delete, name='note_delete'),
]

django_homework/my_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('first_app/', include('first_app.urls')),
    path('accounts/', include("django.contrib.auth.urls")),
    path('first_app/home/', TemplateView.as_view(template_name="home.html"), name="home"),
]

django_homework/first_app/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.

from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class CallOrder(models.Model): # МОДЕЛЬ ДЛЯ ЗАМОВЛЕННЯ ЗВОРОТНОГО ДЗВІНКУ НА САЙТІ (ЗАПИС В БД)
    user_id = models.AutoField(primary_key=True)
    user_name = models.CharField(max_length=30)
    user_surname = models.CharField(max_length=30)
    phone = models.CharField(max_length=15)
    order_date = models.DateTimeField()
    completed_status = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'call_order'


class Delivery(models.Model): # МОДЕЛЬ ДЛЯ ВІДСТЕЖЕННЯ ПОСИЛКИ (ЧИТАННЯ З БД)
    parcel_id = models.CharField(primary_key=True, max_length=20)
    shipment_date = models.DateTimeField()
    delivery_date = models.DateField()
    postal_name = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'delivery'


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    id = models.BigAutoField(primary_key=True)
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class Notes(models.Model): # МОДЕЛЬ ДЛЯ CRUD-ОПЕРАЦІЙ НА ПРИКЛАДІ НОТАТОК
    note_id = models.AutoField(primary_key=True)
    user = models.IntegerField()
    title = models.CharField(max_length=100, blank=True, null=True)
    text = models.CharField(max_length=300, blank=True, null=True)
    reminders = models.DateTimeField(blank=True, null=True)
    category = models.CharField(max_length=30, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'notes'


class SiteAdmins(models.Model):
    admin_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=30)
    surname = models.CharField(max_length=30)
    phone = models.CharField(unique=True, max_length=15)
    status = models.IntegerField()
    notes = models.CharField(max_length=80, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'site_admins'

django_homework/first_app/forms.py
from django import forms
from first_app.models import CallOrder, Notes

class CallOrderForm(forms.ModelForm):
    class Meta:
        model = CallOrder
        fields = ['user_name', 'user_surname', 'phone']

class NoteForm(forms.ModelForm):
    class Meta:
        model = Notes
        fields = ['title', 'text', 'reminders', 'category']

django_homework/first_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from first_app.forms import CallOrderForm, NoteForm
from django.utils import timezone
from first_app.models import Delivery, Notes, AuthUser

from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView

# from django.http import HttpResponse

# def first_view(request):
#     return HttpResponse('Hello, world!')


def home(request):
    return render(request, 'main.html')


def order_call(request):
    if request.method == 'POST':
        form = CallOrderForm(request.POST)
        if form.is_valid():
            call_order = form.save(commit=False)
            call_order.order_date = timezone.now() # додаю поточний час
            call_order.completed_status = False # додаю статус необробленого вхідного запиту
            call_order.save() # запис до бази даних
            user_name = form.cleaned_data['user_name'] # отримую в скрипт потрібне значення з форми
            request.session['user_name'] = user_name # зберігаю дані в сесії для передачі у відображення про успішне заповнення форми
            return redirect('success') # перенаправляю на відображення про успішне заповнення
        else:
            print(form.errors)
    else:
        form = CallOrderForm()
    return render(request, 'order_call.html', {'form': form})


def success(request):
    user_name = request.session.get('user_name') # отримую з сесії, з попереднього відображення, ім'я користувача
    return render(request, 'success.html', {'user_name': user_name})


def tracker(request):
    parcel_data = None
    error_message = None

    if request.method == 'POST':
        parcel_id = request.POST.get('parcel_id', None)
        if parcel_id:
            try:
                parcel_data = Delivery.objects.get(parcel_id=parcel_id)
            except Delivery.DoesNotExist:
                error_message = 'Посилка з введеним трек-номером не знайдена'

    return render(request, 'tracker.html', {'parcel_data': parcel_data, 'error_message': error_message})


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'



@login_required
def note_create(request):
    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            note = form.save(commit=False)
            note.user = request.user.id
            note.save()
            return redirect('note_detail', pk=note.pk)
    else:
        form = NoteForm()
    return render(request, 'note_create.html', {'form': form})


@login_required
def note_detail(request, pk):
    note = get_object_or_404(Notes, pk=pk, user=request.user.id)
    return render(request, 'note_detail.html', {'note': note})

@login_required
def note_list(request):
    notes = Notes.objects.filter(user=request.user.id)
    return render(request, 'note_list.html', {'notes': notes})


@login_required
def note_edit(request, pk):
    note = get_object_or_404(Notes, pk=pk, user=request.user.id)
    if request.method == 'POST':
        form = NoteForm(request.POST, instance=note)
        if form.is_valid():
            form.save()
            return redirect('note_detail', pk=pk)
    else:
        form = NoteForm(instance=note)
    return render(request, 'note_edit.html', {'form': form})


@login_required
def note_delete(request, pk):
    note = get_object_or_404(Notes, pk=pk, user=request.user.id)
    if request.method == 'POST':
        note.delete()
        return redirect('note_list')
    return render(request, 'note_delete.html', {'note': note})

django_homework/first_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Django App{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- Your custom CSS -->
    <!-- <link rel="stylesheet" href="{% static 'css/styles.css' %}"> -->
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-dark">
            <a class="navbar-brand" href="http://127.0.0.1:8000/first_app/">Мій проект</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="http://127.0.0.1:8000/first_app/">Головна<!--<span class="sr-only">(current)</span>--></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="http://127.0.0.1:8000/first_app/call_order/">Замовити дзвінок<!--<span class="sr-only">(current)</span>--></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="http://127.0.0.1:8000/first_app/tracker/">Відстежити посилку<!--<span class="sr-only">(current)</span>--></a>
                    </li>

                    <!-- Add more navigation items here -->
                </ul>
            </div>
        </nav>
    </header>

    <div class="container mt-4">
        {% block content %}
        <!-- Your content goes here -->
        {% endblock %}
    </div>

    <footer class="footer mt-auto py-3 bg-dark">
        <div class="container text-center">
            <span class="text-muted">© 2024 My Django App. All rights reserved.</span>
        </div>
    </footer>

    <!-- Bootstrap JS -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

django_homework/first_app/templates/home.html
{% extends "base.html" %}

{% block title %}Домашня сторінка{% endblock %}

{% block content %}
{% if user.is_authenticated %}
Привіт, {{ user.username }}!

<form action="{% url 'logout' %}" method="post">
    {% csrf_token %}
    <br>
    <button type="submit" class="btn btn-primary">Вийти</button>
</form>

{% else %}
<p>Ви не увійшли в свій профіль</p>
<a href="{% url 'login' %}">Увійти</a>
{% endif %}
{% endblock %}

django_homework/first_app/templates/note_create.html
{% extends 'base.html' %}

{% block title %}
    Create Note
{% endblock %}

{% block content %}
    <h1 class="display-4">Заповніть вашу нотатку</h1><br>
    <form method="post">
        {% csrf_token %}
        <label for="title">Заголовок:</label><br>
        <input type="text" id="title" name="title"><br>
        <label for="text">Текст:</label><br>
        <textarea id="text" name="text"></textarea><br>
        <label for="reminders">Дата нагадування:</label><br>
        <input type="datetime-local" id="reminders" name="reminders"><br>
        <label for="category">Категорія:</label><br>
        <input type="text" id="category" name="category"><br><br>
        <button type="submit">Зберегти</button>
    </form>
{% endblock %}

django_homework/first_app/templates/note_delete.html
{% extends 'base.html' %}

{% block title %}
    Note Delete
{% endblock %}

{% block content %}
    <h1 class="display-4">Видалення нотатки</h1>
    <p>Ви впевнені, що хочете видалити нотатку "{{ note.title }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Видалити</button>
    </form>
{% endblock %}

django_homework/first_app/templates/note_detail.html
{% extends 'base.html' %}

{% block title %}
    Note Detail
{% endblock %}

{% block content %}
    
    <h1 class="display-4">Зміст вашої нотатки:</h1><br>
    <p><strong>Заголовок:</strong> {{ note.title }}</p>
    <p><strong>Текст:</strong> {{ note.text }}</p>
    <p><strong>Дата нагадування:</strong> {{ note.reminders }}</p>
    <p><strong>Категорія:</strong> {{ note.category }}</p><br><br>

    <p><i>Перейти до <a href="http://127.0.0.1:8000/first_app/notes/">списку</a> усіх нотаток</i></p>
    <p><i><a href="{% url 'note_edit' pk=note.pk %}">Редагувати</a> нотатку</i></p>
    <p><i><a href="{% url 'note_delete' pk=note.pk %}">Видалити</a> нотатку</i></p>
{% endblock %}

django_homework/first_app/templates/note_edit.html
{% extends 'base.html' %}

{% block title %}
    Note Edit
{% endblock %}

{% block content %}
    <h1 class="display-4">Редагування нотатки</h1><br>
    
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save Changes</button>
    </form>
{% endblock %}

django_homework/first_app/templates/note_list.html
{% extends 'base.html' %}

{% block title %}
    Note List
{% endblock %}

{% block content %}
    <h1 class="display-4">Ваші нотатки:</h1>
    <ul>
        {% for note in notes %}
            <li><a href="{% url 'note_detail' note.pk %}">{{ note.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

django_homework/first_app/templates/order_call.html
{% extends 'base.html' %}

{% block title %}
    Order Call
{% endblock %}

{% block content %}
<h1 class="display-4">Замовлення зворотного дзвінку</h1>
<p class="lead">Бла-бла-бла... введіть інфу і ми вам передзвонимо...</p>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        Замовити дзвінок
                    </div>
                    <div class="card-body">
                        <!-- Форма замовлення дзвінка -->
                        <form action="{% url 'order_call' %}" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="user_name">Ім'я</label>
                                <input type="text" class="form-control" id="id_user_name" name="user_name" required>
                            </div><br>
                            <div class="form-group">
                                <label for="user_surname">Прізвище</label>
                                <input type="text" class="form-control" id="id_user_surname" name="user_surname" required>
                            </div><br>
                            <div class="form-group">
                                <label for="phone">Номер телефону в форматі: +380хх ххх хх хх</label>
                                <input type="tel" class="form-control" id="id_phone" name="phone" required>
                            </div><br>
                            <button type="submit" class="btn btn-primary">Відправити</button>
                        </form>
                        <!-- Кінець форми -->
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

django_homework/first_app/templates/signup.html
{% extends "base.html" %}

{% block title %}Реєстрація{% endblock %}

{% block content %}
<h2>Реєстрація</h2>
<form method="post">
  {% csrf_token %}
  <!--{{ form }}-->
    <div class="form-group">
        <label for="id_username">Ім'я користувача:</label>
        <br>
        {{ form.username }}
    </div>
    <br>
    <div class="form-group">
        <label for="id_password1">Пароль:</label>
        <br>
        {{ form.password1 }}
    </div>
    <br>
    <div class="form-group">
        <label for="id_password2">Підтвердження паролю:</label>
        <br>
        {{ form.password2 }}
    </div>
  <br>
  <button type="submit" class="btn btn-primary">Зареєструватися</button>
</form>
{% endblock %}

django_homework/first_app/templates/success.html
{% extends 'base.html' %}

{% block title %}
    Success
{% endblock %}

{% block content %}
    <h1>{{ user_name }}, дякуємо за звернення!</h1>
    <p>Ми прийняли ваш запит, очікуйте на дзвінок найближчим часом!</p>
{% endblock %}

django_homework/first_app/templates/tracker.html
{% extends 'base.html' %}

{% block title %}
    Tracker
{% endblock %}

{% block content %}
<h1 class="display-4">Відстеження посилки</h1>
<p class="lead">Введіть трек-номер відправлення для детальної інформації про доставку</p>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        Відстежити посилку
                    </div>
                    <div class="card-body">
                        <!-- Форма замовлення дзвінка -->
                        <form action="{% url 'tracker' %}" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="tracker">Трек-номер</label>
                                <input type="text" class="form-control" id="id_parcel_id" name="parcel_id" required>
                            </div><br>
                            <button type="submit" class="btn btn-primary">Знайти</button>
                        </form>
                        <!-- Кінець форми -->
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% if parcel_data %}
        <h2>Дані про посилку:</h2>
        <p>Трек-номер: {{ parcel_data.parcel_id }}</p>
        <p>Дата і час відправлення: {{ parcel_data.shipment_date }}</p>
        <p>Дата доставки: {{ parcel_data.delivery_date }}</p>
        <p>Служба доставки: {{ parcel_data.postal_name }}</p>
    {% endif %}

    {% if error_message %}
        <p style="color: red;">{{ error_message }}</p>
    {% endif %}
{% endblock %}